name: kairos_fronted
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  collection: 1.18.0
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.4.1
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: 6.1.0
  intl: 0.19.0
  json_path: 0.7.2
  page_transition: 2.1.0
  path_provider: 2.1.4
  path_provider_android: 2.2.10
  path_provider_foundation: 2.4.0
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  provider: 6.1.2
  shared_preferences: 2.3.2
  shared_preferences_android: 2.3.2
  shared_preferences_foundation: 2.5.2
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: 2.4.2
  shared_preferences_windows: 2.4.1
  sqflite: 2.3.3+1
  sqflite_common: 2.5.3
  timeago: 3.6.1
  url_launcher: 6.3.0
  url_launcher_android: 6.3.9
  url_launcher_ios: 6.3.1
  url_launcher_linux: 3.2.0
  url_launcher_macos: 3.2.1
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: 2.3.3
  url_launcher_windows: 3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: MohrRoundedAlt
      fonts:
        - asset: assets/fonts/MohrRoundedAlt-Regular.ttf
        - asset: assets/fonts/MohrRoundedAlt-Thin.ttf
          weight: 100
        - asset: assets/fonts/MohrRoundedAlt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/MohrRoundedAlt-Light.ttf
          weight: 300
        - asset: assets/fonts/MohrRoundedAlt-Medium.ttf
          weight: 500
        - asset: assets/fonts/MohrRoundedAlt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/MohrRoundedAlt-Bold.ttf
          weight: 700

    - family: MohrRounded
      fonts:
        - asset: assets/fonts/MohrRounded-Regular.ttf
        - asset: assets/fonts/MohrRounded-Thin.ttf
          weight: 100
        - asset: assets/fonts/MohrRounded-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/MohrRounded-Light.ttf
          weight: 300
        - asset: assets/fonts/MohrRounded-Medium.ttf
          weight: 500
        - asset: assets/fonts/MohrRounded-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/MohrRounded-Bold.ttf
          weight: 700
        
        

